log_level: INFO
log_file: 'tax_loss.log'
#TODO: Move these filenames to constants and just add data directory as config
portfolio_file: 'data/portfolio.json'
ticker_blacklist_file: 'data/ticker_blacklist.json'
index_weight_file: 'data/IVV_weights.parquet'
price_data_file: 'data/yf_tickers.parquet'
max_stocks: 100 # only consider top x stocks in index (minus blacklisted tickers)
ticker_blacklist_extra: []
optimizer:
  tax_coefficient: 0.7
  max_deviation_from_true_weight: 0.03
  max_total_diviation: 0.75
  cash_constraint: 0.95
  tracking_error_func: 'least_squared'
  lookback_days: 365
